### ISSUE TITLE
No response after executing Scrip: Function getPrivateKey() at xxxxxxxx

### ISSUE THREAD

**Issue by Esperanzaee** [hyugogirubato/KeyDive#12]
![image](https://github.com/hyugogirubato/KeyDive/assets/44806003/5a0ad4ba-f46f-44a4-add3-9ab5563ad033)

![image](https://github.com/hyugogirubato/KeyDive/assets/44806003/bb216b63-2e42-49d1-81e4-30c760b4ae0a)

**Comment by hyugogirubato** [comment]
This is a somewhat random behavior that sometimes happens. In this case, the private key generation function is called but the function to obtain the challenge is not called because the license is hidden somewhere on the site you tested.

What I recommend is to restart your phone and try again, possibly on other DRM sites (free crunchyroll videos) or saka player.

I can also see that the private function hook is generic (all base64), I will add to the project the static name of the private function which is `pukctkiv` in order to reduce the impact of the hook.
