### ISSUE TITLE
Dumping from SDK 34

### ISSUE THREAD

**Issue by Worz01** [hyugogirubato/KeyDive#19]
I installed ghidra but where can I find the elf binary to load onto it? Searched for 'widevine' and 'elf' in program folder and sdk but cannot find it. The functions.md does not hint at where it can be found.

**Comment by hyugogirubato** [comment]
The binary to analyze in ghidra is the widevine binary of your device. To find out which one it is, you must launch the script for the first time and retrieve the binary indicated locally via ADB.

![image](https://github.com/hyugogirubato/KeyDive/assets/65763543/0fc96e9a-b667-4ae3-9b87-381397fd5941)

Sometimes this is not necessary because the SDK may be 34 but the integrated Widevine version is older. Use the script with a functions file only if the script indicates so (puts a warning/error)

**Comment by Worz01** [comment]
> The binary to analyze in ghidra is the widevine binary of your device. To find out which one it is, you must launch the script for the first time and retrieve the binary indicated locally via ADB.
> 
> ![image](https://private-user-images.githubusercontent.com/65763543/344142435-0fc96e9a-b667-4ae3-9b87-381397fd5941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Mzc3MzAsIm5iZiI6MTcxOTYzNzQzMCwicGF0aCI6Ii82NTc2MzU0My8zNDQxNDI0MzUtMGZjOTZlOWEtYjY2Ny00YWUzLTliODctMzgxMzk3ZmQ1OTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA1MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NWY5N2VhYjIyMmJhZjZhZDYwZWI3NmI5NzE3YTZiZWIyNWVhOTkxZjE4ZjI5MWQ2NjBjNzhiNWQzMDQzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFR5D1nVvFM9Suy2elvKV92OhektJE29uGwfKwkRTU8)
> 
> Sometimes this is not necessary because the SDK may be 34 but the integrated Widevine version is older. Use the script with a functions file only if the script indicates so (puts a warning/error)

Thanks for that. Retrieving the binary from adb is in itself a seperate step and including that in the functions.md could be of immense help to newbies.

Also the script gets stuck on hooks completed but no key is generated, and chrome/bitmovin page becomes unresponsive. 

![Untitled](https://github.com/hyugogirubato/KeyDive/assets/126168460/e6e36411-d843-4b3a-b8a0-663141b0bd95)

**Comment by hyugogirubato** [comment]
I plan to do a big update to the library and create a generic way to dump CDMs from an updated version of the player [Axinom](https://github.com/Axinom/drm-sample-player-android). The doc will be updated at that time but I will take your comment into account.

Can you send as an attachment the text result displayed in the console of your terminal so that I can look at what is blocking.

Don't hesitate to ping me directly on discord (same username) for live debugging (sometimes simpler)

**Comment by hyugogirubato** [comment]
Problem resolved via discord discussion. The position of the device_id argument for SDK 34 and above needs to be dynamic/auto-detected. Solution to be implemented in the next update.
