### ISSUE TITLE
"The "functions" attribute is deprecated for SDK API < 34" error

### ISSUE THREAD

**Issue by Pipixel** [hyugogirubato/KeyDive#2]
Hi, everything goes right until I get this error (I just updated in the version 1.0.5, the folder name is not important)

![image](https://github.com/hyugogirubato/KeyDive/assets/66361896/3379fa80-0e60-4159-aeac-f3f383ec4176)

**Comment by hyugogirubato** [comment]
@Pipixel 
As noted, the use of the functions file is unnecessary for versions before sdk 34 simply because the script automatically detects the necessary functions. try using the script without using the function argument and tell me if you get the same result. clearkey has nothing to do since as you see the .so is detected
