### ISSUE TITLE
 KeyDive: Widevine library not found, searching...

### ISSUE THREAD

**Issue by cookieleeuns** [hyugogirubato/KeyDive#23]
![image](https://github.com/user-attachments/assets/e89cf03f-6b86-4d2c-832f-71783c268892)
hello. First of all, thank you so much for developing the program. This may be a bit of a rude question as I don't know much about this field, but when I try to extract the key, I keep getting the above error. How do I fix it?
Thank you for reading and thank you again for developing this program.

**Comment by cookieleeuns** [comment]
![image](https://github.com/user-attachments/assets/dfe3d173-ba36-4fd3-b66a-d726bb20431e)
i reinstalled frida. now its working but now i see this error 😭

**Comment by hyugogirubato** [comment]
Error messages you have are not important here, they will be disabled in the next version to avoid misunderstandings.

Can you dump your Cdm?

**Comment by cookieleeuns** [comment]
I tried again the next day, it worked perfectly and I was able to extract the key. My dream is to be a developer, and I am so grateful for the time and effort you put into developing this program. I respect you 🥰

**Comment by EndofTimee** [comment]
hi. i am having the same problem.

![Image](https://github.com/user-attachments/assets/210e24c2-da59-452e-a192-13e0bb4831e6)

**Comment by frida-dot** [comment]
How you solved widevine liberary not found I also getting this error I'm using magislfrida module and I uninstalled frida and frida server both from the termux but magiskfrida is working fine because it is detected by my pc but when I run keydive I'm getting this error I'm not using any emulator I'm using xiaomi device also I downgraded l1 to l3 with module and I re check that it is now on l3 anyone please help me solve this problem I'm running widevine content on chrome because there is no app for that just a website therefore please help me
