### ISSUE TITLE
'gbk' codec can't decode byte 0xad in position 7564: illegal multibyte sequence

### ISSUE THREAD

**Issue by yiz24** [hyugogirubato/KeyDive#3]
![image](https://github.com/hyugogirubato/KeyDive/assets/64056291/bbd6c254-beda-40d7-a77d-7c68a63e4433)

**Comment by ZS124821** [comment]
经过调试，执行到这里报的错
![image](https://github.com/hyugogirubato/KeyDive/assets/64056291/52f9545d-7f64-4126-9d2f-31b2fc8ff11f)

**Comment by ZS124821** [comment]
正常命令行没问题
![image](https://github.com/hyugogirubato/KeyDive/assets/64056291/5f49890d-994c-4544-be4f-8837bde9c865)

**Comment by hyugogirubato** [comment]
@yiz24 
If you can try to play with reading the function code because this is a text codec problem that I cannot reproduce at home. If you find a solution to overcome this codec problem, do not hesitate to submit it!

**Comment by szescxz** [comment]
Caused by
- using Windows with [ANSI code page set to `cp936`](https://docs.python.org/3/library/locale.html#locale.getencoding)
- some props, likely the mobile operator name (`gsm.operator.alpha`), contains Chinese characters

Solvable by adding `encoding='utf-8'` to every `subprocess.getoutput` call.
Too lazy to submit a PR, sorry.

**Comment by hyugogirubato** [comment]
@szescxz @yiz24 
Thank you for your feedback, I have just corrected the code in the `main` branch.
Fix implemented in the next release.

> https://github.com/hyugogirubato/KeyDive/commit/80da61e0bb316580196089837660c0381beda5b1
