### ISSUE TITLE
Google Pixel 8 Pro // Android 14 // Cdm: Failed to set challenge data: Error parsing message

### ISSUE THREAD

**Issue by Win8Error** [hyugogirubato/KeyDive#35]
Hi hyugogirubato,

keydive failed to extract my Widevine CDM from my Pixel 8 Pro (Android 14). When i enable logging it outputs a suspicious error message `Cdm: Failed to set challenge data: Error parsing message`.

My Pixel runs android 14 and i created a `functions.xml` with Ghidra.

Screenshot:
![2024-09-16 18_58_12-Window](https://github.com/user-attachments/assets/d91da19b-a532-4bff-a507-0b99133372f4)

**Comment by hyugogirubato** [comment]
The challenge parsing error is not a problem because it only impacts the client id which has been dumped correctly. 

Concretely, the private key never passes into the filter function. I recommend that you first re-analyze with ghidra but this time by selecting all possible options for the analysis. If it still does not work, try with another site or another application using DRM very basicly (eg: [axinom_signed.apk](https://github.com/hyugogirubato/KeyDive/blob/main/docs/Axinom/patch/axinom_signed.apk)). And if it still does not work after these two tries, modify the code live to remove the filter function from the known functions. 

However, it is very likely related to the incomplete ghidra analysis. If necessary, you can always contact me on discord for a live debug via teamviewer.

**Comment by hyugogirubato** [comment]
**Thank you for reading my previous message.**

In the worst case, if you can't get it with Android 14 which requires more ease with the process, try with Android 13 or lower.

**Comment by JohnDoe1964** [comment]
If your Pixel 8 is running Android 14 you will need to process with GHidra select analyse all and save as xml use this with Keydive and will give you cdm if you have the correct xml it is also worth using the latest version of frida-server on your rooted device

**Comment by hyugogirubato** [comment]
> I don't think I can downgrade to Android 13 with a Pixel 8, it came pre-installed with 14 when I bought it.
> 
> How do I contact you on discord?

Send me a message using the same username as GitHub
