### ISSUE TITLE
.so can't be found

### ISSUE THREAD

**Issue by mayJ233** [hyugogirubato/KeyDive#42]
wrong with "Core: Library not found: libwvdrmengine.so" , "Script: Library liboemcrypto.so was not found".  on device of xiaomi,Android 13,sdk33

**Comment by hyugogirubato** [comment]
This message is displayed when the library in question is not found because the script automatically tries to deactivate it to force the use of L3. The message itself is not important because it is just information and not an error or a warning, but as you point out, its content is quite disturbing, thus suggesting an error.

I will therefore change the display of this message in debug mode so as not to pollute the standard output of the script.
