### ISSUE TITLE
Question | Extracting L3 from Fire TV Stick

### ISSUE THREAD

**Issue by blackicedbear** [hyugogirubato/KeyDive#46]
I am looking for a cheap way to get an L3 certificate. As I cannot root my Android Phone (Realme 9 Pro+ European model), i thought, if it is possible to extract it from a rooted Fire TV stick.. Is it possible? Or do you have other suggestions?

**Comment by hyugogirubato** [comment]
The easiest way to get an L3 is to make an Android Studio emulator with Android 13 playstore. You then need to root it using [rootAVD](https://github.com/hyugogirubato/KeyDive/blob/main/docs/PACKAGE.md#rootavd) and add the module [MagiskFrida](https://github.com/hyugogirubato/KeyDive/blob/main/docs/PACKAGE.md#magiskfrida).

Otherwise if you have an already rooted device like your FireTV, you can check that Widevine is implemented on your device using the [DRM Info](https://github.com/hyugogirubato/KeyDive/blob/main/docs/PACKAGE.md#drm-info) application if you are not sure. This will avoid having to install android studio which is quite cumbersome (but you must be able to have an adb shell on your root device).

**Comment by blackicedbear** [comment]
Thank you for your reply, I know how to get it from AVD, but it is really annoying, that it will get revoked or blocked after some time. But I will check using DRM Info, but since it can play Prime Video etc., it should work. But I thought, somebody may already tried it.
